name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
    branches: [master]

jobs:

  bof-build:
    name: Build and publish tagged release
    if: startsWith( github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: OS Packages
        run: |
          sudo apt-get update --fix-missing && sudo apt-get -y install \
          git build-essential zlib1g zlib1g-dev wget zip unzip \
          mingw-w64 binutils-mingw-w64 g++-mingw-w64 gcc-multilib jq

      - name: Minisign
        run: |
          MINISIGN_TMP=`mktemp -d`
          cd $MINISIGN_TMP
          wget https://github.com/aead/minisign/releases/download/v0.2.0/minisign-linux-amd64.tar.gz
          tar xvf minisign-linux-amd64.tar.gz
          mv ./minisign ~/minisign
          touch ~/minisign.key && chmod 600 ~/minisign.key
          echo -e "${{ secrets.MINISIGN_PRIVATE_KEY }}" > ~/minisign.key

      - name: Check out code
        uses: actions/checkout@v2

      - name: Git Fetch Tags
        run: git fetch --prune --unshallow --tags -f

      - name: Packages Setup
        run: |
          mkdir packages

      - name: ADCS Enum
        run: |
          ./make_bof.sh adcs_enum

      - name: ADCS Enum COM
        run: |
          ./make_bof.sh adcs_enum_com

      - name: ADCS Enum COM2
        run: |
          ./make_bof.sh adcs_enum_com2

      - name: Adv Audit Policies
        run: |
          ./make_bof.sh adv_audit_policies

      - name: ARP
        run: |
          ./make_bof.sh arp

      - name: Cacls
        run: |
          ./make_bof.sh cacls

      - name: Driver Sigs
        run: |
          ./make_bof.sh driversigs

      - name: Enum Filter Driver
        run: |
          ./make_bof.sh enum_filter_driver

      - name: Enum Local Sessions
        run: |
          ./make_bof.sh enumLocalSessions

      - name: Find Loaded Module
        run: |
          ./make_bof.sh findLoadedModule

      - name: Get Password Policy
        run: |
          ./make_bof.sh get_password_policy

      - name: Get Net Session
        run: |
          ./make_bof.sh get-netsession

      - name: IPConfig
        run: |
          ./make_bof.sh ipconfig

      - name: LDAP Search
        run: |
          ./make_bof.sh ldapsearch

      - name: List DNS
        run: |
          ./make_bof.sh listdns

      - name: List Modules
        run: |
          ./make_bof.sh listmods

      - name: Net Group
        run: |
          ./make_bof.sh netgroup  

      - name: Net Local Group
        run: |
          ./make_bof.sh netlocalgroup

      - name: Net Shares
        run: |
          ./make_bof.sh netshares

      - name: Net Stat
        run: |
          ./make_bof.sh netstat

      - name: "Publish Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./packages/*.tar.gz
            ./packages/*.minisig
